apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0txvd0ZURVRNQkVHQT
    FVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dn
    server: https://e08328fb-02d7-49a6-9f12-b4bdeb98510c.eu-central-2.linodelke.net:443
  name: lke25796

users:
- name: lke25796-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlZ1a29MSDNqVVhXS1YyMjFNNVhJeHFjTFN
    XaXhwYVhNT3FWb2NjTWFOV2MifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZ

contexts:
- context:
    cluster: lke25796
    namespace: default
    user: lke25796-admin
  name: lke25796-ctx

current-context: lke25796-ctx
