# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
    {"apiVersion":"apps/v1","kind":"Deployment",metadata":{"annotations":{}
    ,"labels":{"app":"nccoffee"},  "name":"networkchuckcoffee-deployment"
    ,"namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"nccoffee"}}
    ,"template":{"metadata":{"labels":{"app":"nccoffee"}}
    ,"spec":{"containers":[{"image":"thenetworkchuck/nccoffee:pourover"
    ,"imagePullPolicy":"Always","name":"static-site"
    ,"ports":[{"containerPort":80}]}]}}}}
    creationTimestamp: "2021-05-03T16:07:03Z"
    generation: 1
    labels:
      app: nccoffee
    name: networkchuckcoffee-deployment
    namespace: default
    resourceVersion: "75837"
    uid: c3ca052e-01d6-4083-a9ac-de1f8ff48170
spec:
    progressDeadlineSeconds: 600
    replicas: 3
    revisionHistoryLimit: 10
    selector:
    matchLabels:
      app: nccoffee
